### PR TITLE
Add Svelte template

### PR DESCRIPTION
**Pull request by fartinmartin**
Hey @justintaylor-dev , I took a swing at adding a svelte-template and things appear to be working well! Two notes:

1. In the current state the svelte output doesn't include the resulting CSS from the `src/js/index.scss` or `src/js/variables.scss` Sass files. I may have some more time this weekend to look into this further.
2. If you don't include any styles in your Svelte components the `vite-cep-plugin` fails to map over a null value of `cssFileNames` in the `html-template.js` function. See [`vite-cep-plugin` #11](https://github.com/hyperbrew/vite-cep-plugin/pull/11)

### CODE REVIEW

**Comment by justintaylor-dev** [comment]
Thanks! Merged the plugin changes, checking this out now

**Review by justintaylor-dev — APPROVED** [review]

**Comment by justintaylor-dev** [comment]
@fartinmartin Thanks for getting a jump start on this!

Your fix for the plugin seems to work, so bumped that version.

I moved the dependencies to dev, since Svelte isn't needed at runtime.

From what I can tell it's working in `dev` but not on `build`. I keep getting this error:
```
Uncaught TypeError: Cannot read properties of undefined (reading '$$')
```
Seems to be a Svelte thing. String templates seem to be throwing it off, so tried replacing those with standard strings but still getting this error. Maybe take a look when you get chance:

image

If you can merge changes from the `template-svelte` branch and proceed, that would be great. Thanks!

**Review by justintaylor-dev — CHANGES_REQUESTED** [review]
Works on dev, still not on build. Getting

```
Uncaught TypeError: Cannot read properties of undefined (reading '$$')
```

**Comment by fartinmartin** [comment]
Hey Justin, thanks for taking a look!

I've merged the changes from the `template-svelte` branch into my fork's `master`, but am unable to recreate your error. 

It's likely user error on my part—can you walk me through how you are running the `build` output in your browser to get that error?

Starting from a fresh clone of my fork and running:
- `yarn`
- [edit `cep.config.ts` to have `jsxBin: "off"` since I'm on M1]
- `yarn build`
- `yarn serve`

Should I expect to see the React panel served at `http://localhost:5000/main/`? Is that how you are seeing the `Uncaught TypeError` when replacing the `src/js/main` contents with the `src/js/template-svelte` contents?

**Comment by justintaylor-dev** [comment]
@fartinmartin as of now, to test out the svelte template:

1. Rename the `main` to `template-main`
2. Rename `template-svelte` to `main`
3. Run `yarn build` 
4. View in Adobe App or if you want to test in the browser, run `yarn serve`

Any folder starting with `template-` gets ignored, those are used for `yarn create bolt-cep`.

If you follow those steps and the svelte template is building properly, can you provide all your specs? (OS version, Node version, Yarn version, etc)

Thanks!

**Comment by justintaylor-dev** [comment]
@fartinmartin okay made some improvements for easier testing of different frameworks if you wanna merge the latest changes from `template-svelte`

- Fixed the port issue, was serving to the default one, now it serves to 5000 like it should.
- You can now test all the template by enabling line 48 in `cep.config.ts`

```
// ...debugAll, // DEBUG-ONLY
```

Build, then serve, then you'll get a panel for each framework:

image

All 3 work in dev.

React and Vue work on build, Svelte still fails with `Uncaught TypeError: Cannot read properties of undefined (reading '$$')`

Thanks!

**Comment by justintaylor-dev** [comment]
@fartinmartin root div id was wrong 🤦‍♂️. It's working now!

image

**Comment by justintaylor-dev** [comment]
@fartinmartin closing this one out and merging in: https://github.com/hyperbrew/bolt-cep/pull/26

Thanks for your help!

**Comment by fartinmartin** [comment]
Awesome!! 🥳

**Pull request closed without merging**
